#' Add Matchup of the Week Flags to Matchup Data
#'
#' Seeds the initial MotW matchup in week 1, then chains forward each week so
#' the prior week's MotW winner faces a new opponent. Also computes the number
#' of shots each losing team would take (starters who scored <10 pts, with an
#' extra shot for any starter scoring negative).
#'
#' @param matchup_data team-level matchup data from \code{get_team_matchups()}
#' @param week_1_matchup_id the \code{matchup_id} of the designated week-1 MotW game
#' @param max_week the final week to calculate MotW through (inclusive)
#' @param player_data player-level data from \code{get_all_matchups_data()},
#'   used to compute shot counts
#'
#' @return \code{matchup_data} with added columns \code{motw} (1 = MotW game,
#'   NA otherwise) and \code{# of Shots}
#' @export
add_motw_to_matchups <-
  function(matchup_data,
           week_1_matchup_id,
           max_week,
           player_data) {
    # add MotW starting value to matchups
    matchup_data$motw <- NA
    matchup_data[(matchup_data$matchup_id == week_1_matchup_id) &
                   (matchup_data$week == 1), 'motw'] <- 1

    # add remaining MotW values to matchups
    if (max_week > 1) {
      for (week_num in 2:max_week) {
        # get previous week
        prev_week <- week_num - 1

        # get last winner of motw
        prev_motw_winners <- matchup_data %>%
          filter(week == prev_week, winner == 1, motw == 1) %>%
          pull(manager_id)

        # Iterate over each previous week's loser and assign motw
        for (prev_motw_winner in prev_motw_winners) {
          matchup_data <- matchup_data %>%
            mutate(motw = ifelse(week == week_num &
                                   manager_id == prev_motw_winner, 1, motw))
        }

        # get the matchup id of the losers game
        this_week_matchup_id <- matchup_data %>%
          filter(week == week_num, motw == 1) %>%
          pull(matchup_id)

        # Check if this_week_matchup_id is not empty before attempting mutate
        if (!is.null(this_week_matchup_id) && length(this_week_matchup_id) > 0) {
          # assign motw to the losers opponent
          matchup_data <- matchup_data %>%
            mutate(motw = ifelse(
              week == week_num & matchup_id == this_week_matchup_id,
              1,
              motw
            ))
        }
      }
    }
    shots_data <- player_data %>%
      filter(starter_id == 1) %>%
      group_by(week, manager_id) %>%
      summarise(`# of Shots` = sum(points < 10) + sum(points < 0))

    output_data <-
      matchup_data %>% left_join(shots_data, by = c("week", "manager_id"))
    return(output_data)
  }



#' Create the MotW Summary Table
#'
#' Summarizes each week's Matchup of the Week result: winner team, loser team,
#' scores, and shots the loser would drink.
#'
#' @param motw_data result of \code{add_motw_to_matchups()}
#'
#' @return a data frame with one row per MotW week and columns
#'   \code{Winner Team}, \code{Winner Score}, \code{Loser Score},
#'   \code{Loser Team}, \code{# of Shots/Dogs}
#' @export
create_motw_table <- function(motw_data) {
  motw_table <- motw_data %>%
    filter(motw == 1) %>%
    group_by(week) %>%
    arrange(matchup_id) %>%
    reframe(
      Week = week,
      `Winner Team` = team_name[which.max(winner)],
      `Winner Score` = max(team_points),
      `Loser Score` = min(team_points),
      `Loser Team` = team_name[which.min(winner)],
      `# of Shots/Dogs` = `# of Shots`[which.min(winner)]
    ) %>%
    distinct() %>%
    select(-week)

  return(motw_table)
}


#' Create the MotW Danger Table
#'
#' Reads pre-computed MotW simulation CSV files (generated by the companion
#' Python script) and returns a table summarising each team's Danger Meter
#' (probability of having to take shots) under different outcome scenarios.
#'
#' @details This function reads three CSV files from a \code{currentMotW/}
#'   subdirectory relative to the working directory:
#'   \code{matchup_tree.csv}, \code{matchup_tree_left.csv}, and
#'   \code{matchup_tree_right.csv}. These files must be generated by
#'   \code{motw.py} before calling this function.
#'
#' @return a data frame with columns \code{Team}, \code{NPG} (next potential
#'   game), \code{RPA} (rounds potentially affected), \code{DM} (danger meter
#'   %), and conditional DM columns for each current matchup outcome
#' @export
create_danger_table <- function() {
  # create danger table and visual
  tree <-
    read.csv('currentMotW/matchup_tree.csv')
  left_tree <-
    read.csv('currentMotW/matchup_tree_left.csv')
  right_tree <-
    read.csv('currentMotW/matchup_tree_right.csv')
  tree$Count <- 0.5
  left_tree$Count <- 0.5
  right_tree$Count <- 0.5

  Current_Champion <- tree$Champion[1]
  Current_Opponent <- tree$Opponent[1]

  tree_champ <- tree[, c(1, 2, 4)]
  tree_opp <- tree[, c(1, 3, 4)]
  names(tree_opp) <- names(tree_champ)
  tree <- rbind(tree_champ, tree_opp)
  names(tree) <- c('Week', 'Team', 'Count')

  left_tree_champ <- left_tree[, c(1, 2, 4)]
  left_tree_opp <- left_tree[, c(1, 3, 4)]
  names(left_tree_opp) <- names(left_tree_champ)
  left_tree <- rbind(left_tree_champ, left_tree_opp)
  names(left_tree) <- c('Week', 'Team', 'Count')

  right_tree_champ <- right_tree[, c(1, 2, 4)]
  right_tree_opp <- right_tree[, c(1, 3, 4)]
  names(right_tree_opp) <- names(right_tree_champ)
  right_tree <- rbind(right_tree_champ, right_tree_opp)
  names(right_tree) <- c('Week', 'Team', 'Count')

  df <- tree %>% group_by(Team) %>%
    dplyr::summarize('NPG' = min(Week),
                     'RPA' = n(),)

  tree$Week <- as.factor(tree$Week)
  left_tree$Week <- as.factor(left_tree$Week)
  right_tree$Week <- as.factor(right_tree$Week)

  dt <- tree %>%
    dplyr::group_by(Week, Team) %>%
    dplyr::tally() %>%
    dplyr::mutate(percent = n / sum(n))

  safety <- dt %>% dplyr::group_by(Team) %>%
    dplyr::summarize(`DM` = round(100 * sum(percent)))

  left_dt <- left_tree %>%
    dplyr::group_by(Week, Team) %>%
    dplyr::tally() %>%
    dplyr::mutate(percent = n / sum(n))

  left_safety <- left_dt %>% dplyr::group_by(Team) %>%
    dplyr::summarize("{Current_Champion} Win DM" := round(100 * sum(percent)))

  right_dt <- right_tree %>%
    dplyr::group_by(Week, Team) %>%
    dplyr::tally() %>%
    dplyr::mutate(percent = n / sum(n))

  right_safety <- right_dt %>% dplyr::group_by(Team) %>%
    dplyr::summarize("{Current_Opponent} Win DM" := round(100 * sum(percent)))

  df <- merge(x = df,
              y = safety,
              by = "Team",
              all.x = TRUE)
  df <- merge(x = df,
              y = left_safety,
              by = "Team",
              all.x = TRUE)
  df <- merge(x = df,
              y = right_safety,
              by = "Team",
              all.x = TRUE)

  df[, 3:6][is.na(df[, 3:6])] <- 0

  df <- df %>% arrange(NPG, -DM)

  return(df)
}

#' Plot the MotW Danger Chart
#'
#' Reads the main MotW simulation CSV (\code{currentMotW/matchup_tree.csv}) and
#' returns a stacked bar chart showing each team's probability of having to take
#' shots by future week.
#'
#' @details Requires \code{currentMotW/matchup_tree.csv} to exist (generated by
#'   \code{motw.py}).
#'
#' @return a ggplot2 object
#' @export
create_danger_chart <- function() {
  tree <-
    read.csv('currentMotW/matchup_tree.csv')
  tree$Count <- 0.5

  tree_champ <- tree[, c(1, 2, 4)]
  tree_opp <- tree[, c(1, 3, 4)]
  names(tree_opp) <- names(tree_champ)
  tree <- rbind(tree_champ, tree_opp)
  names(tree) <- c('Week', 'Team', 'Count')

  tree$Week <- as.factor(tree$Week)

  dt <- tree %>%
    dplyr::group_by(Week, Team) %>%
    dplyr::tally() %>%
    dplyr::mutate(percent = n / sum(n))

  week_plot <-
    ggplot(data = dt, aes(x = Week, y = percent, fill = Team)) +
    geom_bar(stat = 'identity', position = "fill") +
    geom_text(
      aes(label = paste0(sprintf(
        "%1.1f", percent * 100
      ), "%")),
      position = position_fill(vjust = 0.5),
      colour = "white",
      size = 3
    ) +
    coord_flip() +
    scale_fill_manual(values = rcartocolor::carto_pal(12, "Safe")) +
    theme_classic() +
    scale_x_discrete(limits = rev) +
    labs(x = 'Week', y = 'Chance to Lose MotW',
         title = 'Who Will Have to Take Shots?')

  return(week_plot)
}
